[package]
name = "discord_group_pic_rs"
version = "0.1.0"
authors = ["Yufan Lou <2263580+louy2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
anyhow = "1.0.39"
dashmap = "4.0.2"
tokio-stream = "0.1.4"
image = "0.23.14"
rand = "0.8.3"
rusttype = "0.9.2"

[dependencies.serenity]
version = "0.10.4"
features = ["default", "collector"]
# git = "https://github.com/nickelc/serenity.git"
# branch = "tokio-1.0/reqwest"

[dependencies.tokio]
version = "1.3"
features = ["full"]
