[package]
name = "discord_group_pic_rs"
version = "0.1.0"
authors = ["Yufan Lou <2263580+louy2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
anyhow = "1.0.38"
dashmap = "4.0.2"
tokio-stream = "0.1.2"

[dependencies.serenity]
version = "0.10.2"
features = ["default", "collector"]
# git = "https://github.com/nickelc/serenity.git"
# branch = "tokio-1.0/reqwest"

[dependencies.tokio]
version = "1.3"
features = ["full"]
