[package]
name = "discord_group_pic_rs"
version = "0.1.0"
authors = ["Yufan Lou <2263580+louy2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
image = "0.23"
rand = "0.8"
rusttype = "0.9"
twilight-model = "0.7"
twilight-http = { version = "0.7", features = ["tracing"] }
twilight-gateway = "0.7"
twilight-util = { version = "0.7", features = ["builder"]}
lazy_static = "1"
