[package]
name = "discord_group_pic_rs"
version = "0.1.0"
authors = ["Yufan Lou <2263580+louy2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
anyhow = "1.0.37"

[dependencies.serenity]
# version = "0.9"
git = "https://github.com/louy2/serenity.git"
branch = "add-static-face"

[dependencies.tokio]
version = "1"
features = ["full"]
